import { AuthLayout } from "@/components/auth/AuthLayout";
import { buildMetadata } from "@/lib/seo";
import type { Metadata } from "next";
import { ClaimForm } from "./ClaimForm";

export const metadata: Metadata = buildMetadata({
  title: "Set your password",
  pathname: "/claim",
  noIndex: true,
});

// Landing page for the one-time "claim your account" link generated by
// scripts/migrate-clerk-users.mjs for every user migrated off Clerk — see
// PLAN-backend-auth-migration.md.
export default async function ClaimPage({
  searchParams,
}: {
  searchParams: Promise<{ token?: string }>;
}) {
  const { token } = await searchParams;

  return (
    <AuthLayout>
      {token ? (
        <>
          <div className="text-center max-w-sm">
            <h1 className="text-lg font-medium">Welcome back</h1>
            <p className="mt-1 text-sm text-text-secondary">
              Readable now uses email + password sign-in. Set a password for your account to continue.
            </p>
          </div>
          <ClaimForm token={token} />
        </>
      ) : (
        <p className="text-sm text-text-secondary text-center max-w-sm">
          This link is missing its claim token. Use the link you were sent to set your password.
        </p>
      )}
    </AuthLayout>
  );
}
